web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.example.com'
  ports:
    - '80:80'
    - '443:443'
    - '2222:22'
  volumes:
    - g/RSV/gigabit/con-fig:/etc/gigabit
    - i/RSV/git lab/logs:/var/log/'gitlab
    - l/RSV/git lab/data:/var/opt/'gitlab

